### ISSUE TITLE
Control color of edges

### ISSUE THREAD

**Issue by FinScience** [mattflor/chorddiag#11]
Is it possible to control the color of the nodes and the chords? I wish to specify which node will get what color and which chord will get what color

**Comment by mattflor** [comment]
Well, you can certainly specify group colors. Here's an example from the package vignette:

```r
library(chorddiag)
m <- matrix(c(11975,  5871, 8916, 2868,
              1951, 10048, 2060, 6171,
              8010, 16145, 8090, 8045,
              1013,   990,  940, 6907),
            byrow = TRUE,
            nrow = 4, ncol = 4)
haircolors <- c("black", "blonde", "brown", "red")
dimnames(m) <- list(have = haircolors,
                    prefer = haircolors)
print(m)
groupColors <- c("#000000", "#FFDD89", "#957244", "#F26223")
chorddiag(m, groupColors = groupColors, groupnamePadding = 50)
```

The chords are then colored automatically based on the size of the target group so that you can infer visually the more dominant direction.
E.g., with the hair color data above, the chord between the blonde and red groups is colored RED which means that there are more blonde people (source) who prefer red-haired partners (target) than there are red-haired people (source) with a preference for blondes (target) ...

**Comment by FinScience** [comment]
Thanks for the quick response. However my use case is a bit different. The following example might make it clear. My adjacency matrix

                       A     B     C     D
               A      0    10     5     11
               B      30    0     6     12
               C      11    9     0     0
               D      16    17   18     0

 I am looking for a way so that I can specify that the color of the chord between A-B, A-C,B-D,D-C are red and rest of them are green symbolizing that some routes are pending whereas others are covered. Is there a way to achieve this? I tried using type="bipartite" but that is randomly assigning the colors. Any help would be great as I can't find any other visualization package in R that can solve my case better than this.

**Comment by flopesdematos** [comment]
Hi,

I'm also interested in an option that allows to personalise the chords colours (for instance, using the same colour in all), independently of the source or target bands.

Is possible to include this parameter in the near future?

Thank you,
Fábio

**Comment by mattflor** [comment]
I have to think a bit more deeply how to implement this properly. But for now you can install a branch I created:

```r
devtools::install_github("mattflor/chorddiag", ref = "issue-11-chord-colors")
```

There's a new (yet undocumented) option `chordColors`. Default is NULL which keeps the original behaviour. But you can provide a matrix (same size that your data has) with color specifications (see example below). Because the d3 chord layout still decides which color to use (A -> B or B -> A?) you will most likely get your desired colors by using a symmetric color matrix.

Here's the example:
```r
library(chorddiag)
m <- matrix(c(0, 10, 5, 11,
              30, 0, 6, 12,
              11, 9, 0, 0,
              16, 17, 18, 0),
            byrow = TRUE,
            nrow = 4, ncol = 4)
groupnames <- LETTERS[1:4]
dimnames(m) <- list(source = groupnames,
                    target = groupnames)

chordcolors <- matrix(rep("green", 16), byrow = TRUE, nrow = 4)
chordcolors[1, 2] <- chordcolors[2, 1] <- "red"
chordcolors[1, 3] <- chordcolors[3, 1] <- "#d7191c"
chordcolors[2, 4] <- chordcolors[4, 2] <- "#d7191c"
chordcolors[3, 4] <- chordcolors[4, 3] <- "#d7191c"

print(m)
print(chordcolors)
chorddiag(m, groupnamePadding = 50,
          chordColors = chordcolors)
```

**Comment by FinScience** [comment]
Thanks for this. Really helpful

**Comment by flopesdematos** [comment]
Thanks for the quick solution!
